### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by TornaxO7** [jeandudey/linux-personality#1]
Hi!

May I ask if you could please update all dependencies and release a new version? Some features in your code will be probably rejected in future rust versions.

![peepoShy](https://github.com/user-attachments/assets/e97ed599-1a80-43b0-b0ef-f8c80c0c42e6)

https://github.com/orhun/binsider/issues/61

**Comment by jeandudey** [comment]
I've updated the bitflags dependency to 2 and also released version 2 of the crate, there are some breaking changes due to the bitflags update though.
